#!/usr/bin/env bash
set -Eeuo pipefail

IFS=$'\t\n'

run-apply() {
	xsltproc spring/spring.xslt pom.xml \
	| unexpand -t2 > spring/pom.xml
}

run-update() {
	run-apply
    mvn \
        spotless:apply \
        versions:update-properties \
        versions:update-parent \
        versions:commit
}

"run-${@:-usage}"
