#!/usr/bin/env bash
set -Eeuo pipefail

IFS=$'\t\n'

run-update() {
		xsltproc spring/spring.xslt pom.xml \
		| unexpand -t2 > spring/pom.xml
    mvn \
        spotless:apply \
        versions:update-properties \
        versions:update-parent \
        versions:commit
}

run-${@:-help}
